### ISSUE TITLE
"No data" - optional text

### ISSUE THREAD

**Issue by martonaron** [datadirr/flutter_dropdown_plus#1]
Hello, you made a fantastic package, and I'm thankful for you made it available for anybody.
If I can ask a little modification, I'd happy to see an option to modify ''No data'' text, what is shown when there's no list item to be showned.

**Comment by datadirr** [comment]
Thank you for using our package and give a feedback.
Now version 1.2.0 with available noDataWidget option for "No Data" widget customisation.

**Comment by datadirr** [comment]
Hello,

Thank you for using our package and giving feedback.
Now version 1.2.0 with available noDataWidget option for "No Data" widget
customisation.

Best regards,
@datadirr
